apiVersion: v1
kind: policy
spec:
  platform: windows
  name: 'STIG - Ensure ''Internet Zone Run NETFramework Reliant Components Signed With Authenticode'' is set to ''Enabled'''
  query: >-
    SELECT 1 FROM mdm_bridge WHERE mdm_command_input = '<SyncBody><Get><CmdID>1</CmdID><Item><Target><LocURI>./Device/Vendor/MSFT/Policy/Config/InternetExplorer/InternetZoneRunNETFrameworkReliantComponentsSignedWithAuthenticode</LocURI></Target></Item></Get></SyncBody>' AND mdm_command_output LIKE '%<enabled/>%';
  purpose: Informational
  tags: framework:DISA-STIG, benchmark:DISA-STIG, platform:windows, control:internetexplorer-internetzonerunnetframeworkreliantcomponentssignedwithauthenticode
  description: 'STIG setting: ./Device/Vendor/MSFT/Policy/Config/InternetExplorer/InternetZoneRunNETFrameworkReliantComponentsSignedWithAuthenticode'
  resolution: 'To establish the recommended configuration via configuration profiles, set the following Settings Catalog path. Policy\Config\InternetExplorer\InternetZoneRunNETFrameworkReliantComponentsSignedWithAuthenticode'