apiVersion: v1
kind: policy
spec:
  platform: windows
  name: 'STIG - Ensure ''Internet Zone Allow Access To Data Sources'' is set to ''Enabled'''
  query: SELECT 1 FROM mdm_bridge WHERE mdm_command_input = '<SyncBody><Get><CmdID>1</CmdID><Item><Target><LocURI>./Device/Vendor/MSFT/Policy/Result/InternetExplorer/InternetZoneAllowAccessToDataSources</LocURI></Target></Item></Get></SyncBody>' AND mdm_command_output LIKE '%<Enabled/>%';
  purpose: Informational
  tags: framework:DISA-STIG, benchmark:DISA-STIG, platform:windows, control:internetexplorer-internetzoneallowaccesstodatasources
  description: 'STIG setting: ./Device/Vendor/MSFT/Policy/Config/InternetExplorer/InternetZoneAllowAccessToDataSources'
  resolution: 'To establish the recommended configuration via configuration profiles, set the following Settings Catalog path. Policy\Config\InternetExplorer\InternetZoneAllowAccessToDataSources'