apiVersion: v1
kind: policy
spec:
  platform: windows
  name: 'STIG - Ensure ''Allow Local Ipsec Policy Merge'' is set to ''Disabled'''
  query: >-
    SELECT 1 FROM mdm_bridge WHERE mdm_command_input = '<SyncBody><Get><CmdID>1</CmdID><Item><Target><LocURI>./Vendor/MSFT/Firewall/MdmStore/PublicProfile/AllowLocalIpsecPolicyMerge</LocURI></Target></Item></Get></SyncBody>' AND mdm_command_output = 'false';
  purpose: Informational
  tags: framework:DISA-STIG, benchmark:DISA-STIG, platform:windows, control:allowlocalipsecpolicymerge-false
  description: 'This value is an on/off switch. If this value is false, connection security rules from the local store are ignored and not enforced, regardless of the schema version and connection security rule version. The merge law for this option is to always use the value of the GroupPolicyRSoPStore.'
  resolution: 'To establish the recommended configuration via configuration profiles, set the following Settings Catalog path. MdmStore\PublicProfile\AllowLocalIpsecPolicyMerge'