apiVersion: v1
kind: policy
spec:
  platform: windows
  name: 'STIG - Ensure ''Device Password History'' is set to ''24'''
  query: SELECT 1 FROM mdm_bridge WHERE mdm_command_input = '<SyncBody><Get><CmdID>1</CmdID><Item><Target><LocURI>./Device/Vendor/MSFT/Policy/Result/DeviceLock/DevicePasswordHistory</LocURI></Target></Item></Get></SyncBody>' AND mdm_command_output = '24';
  purpose: Informational
  tags: framework:DISA-STIG, benchmark:DISA-STIG, platform:windows, control:win11-stig-v2r4:devicelock-devicepasswordhistory
  description: 'Specifies how many passwords can be stored in the history that can’t be used.'
  resolution: 'To establish the recommended configuration via configuration profiles, set the following Settings Catalog path. Policy\Config\DeviceLock\DevicePasswordHistory'