apiVersion: v1
kind: policy
spec:
  platform: windows
  name: 'STIG - Ensure ''Device Password Expiration'' is set to ''60'''
  query: SELECT 1 FROM mdm_bridge WHERE mdm_command_input = '<SyncBody><Get><CmdID>1</CmdID><Item><Target><LocURI>./Device/Vendor/MSFT/Policy/Result/DeviceLock/DevicePasswordExpiration</LocURI></Target></Item></Get></SyncBody>' AND mdm_command_output = '60';
  purpose: Informational
  tags: framework:DISA-STIG, benchmark:DISA-STIG, platform:windows, control:win11-stig-v2r4:devicelock-devicepasswordexpiration
  description: 'Specifies when the password expires (in days).'
  resolution: 'To establish the recommended configuration via configuration profiles, set the following Settings Catalog path. Policy\Config\DeviceLock\DevicePasswordExpiration'