apiVersion: v1
kind: policy
spec:
  platform: windows
  name: 'STIG - Ensure ''Allow Windows Consumer Features'' is set to ''Disabled'''
  query: >-
    SELECT 1 FROM mdm_bridge WHERE mdm_command_input = '<SyncBody><Get><CmdID>1</CmdID><Item><Target><LocURI>./Device/Vendor/MSFT/Policy/Config/Experience/AllowWindowsConsumerFeatures</LocURI></Target></Item></Get></SyncBody>' AND mdm_command_output = '0';
  purpose: Informational
  tags: framework:DISA-STIG, benchmark:DISA-STIG, platform:windows, control:win11-stig-v2r4:allowwindowsconsumerfeatures-0
  description: 'Prior to Windows 10, version 1803, this policy had User scope. This policy allows IT admins to turn on experiences that are typically for consumers only, such as Start suggestions, Membership notifications, Post-OOBE app install and redirect tiles. Most restricted value is 0.'
  resolution: 'To establish the recommended configuration via configuration profiles, set the following Settings Catalog path. Policy\Config\Experience\AllowWindowsConsumerFeatures'