apiVersion: v1
kind: policy
spec:
  platform: windows
  name: 'STIG - Ensure ''IPv6Source Routing Protection Level'' is set to ''Enabled'''
  query: SELECT 1 FROM mdm_bridge WHERE mdm_command_input = '<SyncBody><Get><CmdID>1</CmdID><Item><Target><LocURI>./Device/Vendor/MSFT/Policy/Result/MSSLegacy/IPv6SourceRoutingProtectionLevel</LocURI></Target></Item></Get></SyncBody>' AND mdm_command_output LIKE '%<Enabled/>%';
  purpose: Informational
  tags: framework:DISA-STIG, benchmark:DISA-STIG, platform:windows, control:win11-stig-v2r4:msslegacy-ipv6sourceroutingprotectionlevel
  description: 'STIG setting: ./Device/Vendor/MSFT/Policy/Config/MSSLegacy/IPv6SourceRoutingProtectionLevel'
  resolution: 'To establish the recommended configuration via configuration profiles, set the following Settings Catalog path. Policy\Config\MSSLegacy\IPv6SourceRoutingProtectionLevel'