apiVersion: v1
kind: policy
spec:
  platform: windows
  name: 'STIG - Ensure ''Allow Game DVR'' is set to ''Disabled'''
  query: >-
    SELECT 1 FROM mdm_bridge WHERE mdm_command_input = '<SyncBody><Get><CmdID>1</CmdID><Item><Target><LocURI>./Device/Vendor/MSFT/Policy/Config/ApplicationManagement/AllowGameDVR</LocURI></Target></Item></Get></SyncBody>' AND mdm_command_output = '0';
  purpose: Informational
  tags: framework:DISA-STIG, benchmark:DISA-STIG, platform:windows, control:win11-stig-v2r4:applicationmanagement-allowgamedvr
  description: 'Note The policy is only enforced in Windows 10 for desktop. Specifies whether DVR and broadcasting is allowed. Most restricted value is 0.'
  resolution: 'To establish the recommended configuration via configuration profiles, set the following Settings Catalog path. Policy\Config\ApplicationManagement\AllowGameDVR'