apiVersion: v1
kind: policy
spec:
  platform: windows
  name: 'STIG - Ensure ''Device Password Enabled'' is set to ''Disabled'''
  query: >-
    SELECT 1 FROM mdm_bridge WHERE mdm_command_input = '<SyncBody><Get><CmdID>1</CmdID><Item><Target><LocURI>./Device/Vendor/MSFT/Policy/Config/DeviceLock/DevicePasswordEnabled</LocURI></Target></Item></Get></SyncBody>' AND mdm_command_output = '0';
  purpose: Informational
  tags: framework:DISA-STIG, benchmark:DISA-STIG, platform:windows, control:win10-stig-v3r4:devicelock-devicepasswordenabled
  description: 'Specifies whether device lock is enabled.'
  resolution: 'To establish the recommended configuration via configuration profiles, set the following Settings Catalog path. Policy\Config\DeviceLock\DevicePasswordEnabled'