apiVersion: v1
kind: policy
spec:
  platform: windows
  name: 'STIG - Ensure ''Turn Off Data Execution Prevention For Explorer'' is set to ''Disabled'''
  query: >-
    SELECT 1 FROM mdm_bridge WHERE mdm_command_input = '<SyncBody><Get><CmdID>1</CmdID><Item><Target><LocURI>./Device/Vendor/MSFT/Policy/Config/FileExplorer/TurnOffDataExecutionPreventionForExplorer</LocURI></Target></Item></Get></SyncBody>' AND mdm_command_output LIKE '%<disabled/>%';
  purpose: Informational
  tags: framework:DISA-STIG, benchmark:DISA-STIG, platform:windows, control:win10-stig-v3r4:fileexplorer-turnoffdataexecutionpreventionforexplorer
  description: 'STIG setting: ./Device/Vendor/MSFT/Policy/Config/FileExplorer/TurnOffDataExecutionPreventionForExplorer'
  resolution: 'To establish the recommended configuration via configuration profiles, set the following Settings Catalog path. Policy\Config\FileExplorer\TurnOffDataExecutionPreventionForExplorer'