apiVersion: v1
kind: policy
spec:
  platform: windows
  name: 'STIG - Ensure ''Interactive Logon Message Text For Users Attempting To Log On'' is set to ''Enabled'''
  query: >-
    SELECT 1 FROM mdm_bridge WHERE mdm_command_input = '<SyncBody><Get><CmdID>1</CmdID><Item><Target><LocURI>./Device/Vendor/MSFT/Policy/Config/LocalPoliciesSecurityOptions/InteractiveLogon_MessageTextForUsersAttemptingToLogOn</LocURI></Target></Item></Get></SyncBody>' AND mdm_command_output = '1';
  purpose: Informational
  tags: framework:DISA-STIG, benchmark:DISA-STIG, platform:windows, control:win10-stig-v3r4:interactivelogon-messagetextforusersattemptingtologon
  description: 'Interactive logon: Message text for users attempting to log on This security setting specifies a text message that is displayed to users when they log on. This text is often used for legal reasons, for example, to warn users about the ramifications of misusing company information or to warn them that their actions may be audited. Default: No message.'
  resolution: 'To establish the recommended configuration via configuration profiles, set the following Settings Catalog path. Policy\Config\LocalPoliciesSecurityOptions\InteractiveLogon_MessageTextForUsersAttemptingToLogOn'