apiVersion: v1
kind: policy
spec:
  platform: windows
  name: 'STIG - Ensure ''Prevent Override For Files In Shell'' is set to ''Enabled'''
  query: >-
    SELECT 1 FROM mdm_bridge WHERE mdm_command_input = '<SyncBody><Get><CmdID>1</CmdID><Item><Target><LocURI>./Device/Vendor/MSFT/Policy/Config/SmartScreen/PreventOverrideForFilesInShell</LocURI></Target></Item></Get></SyncBody>' AND mdm_command_output = '1';
  purpose: Informational
  tags: framework:DISA-STIG, benchmark:DISA-STIG, platform:windows, control:win10-stig-v3r4:smartscreen-preventoverrideforfilesinshell
  description: 'Allows IT Admins to control whether users can ignore SmartScreen warnings and run malicious files.'
  resolution: 'To establish the recommended configuration via configuration profiles, set the following Settings Catalog path. Policy\Config\SmartScreen\PreventOverrideForFilesInShell'