apiVersion: v1
kind: policy
spec:
  platform: windows
  name: 'STIG - Ensure ''Access Credential Manager As Trusted Caller'' is set to ''Enabled'''
  query: SELECT 1 FROM mdm_bridge WHERE mdm_command_input = '<SyncBody><Get><CmdID>1</CmdID><Item><Target><LocURI>./Device/Vendor/MSFT/Policy/Result/UserRights/AccessCredentialManagerAsTrustedCaller</LocURI></Target></Item></Get></SyncBody>' AND mdm_command_output = '1';
  purpose: Informational
  tags: framework:DISA-STIG, benchmark:DISA-STIG, platform:windows, control:win10-stig-v3r4:userrights-accesscredentialmanagerastrustedcaller
  description: 'This user right is used by Credential Manager during Backup/Restore. No accounts should have this privilege, as it is only assigned to Winlogon. Users'' saved credentials might be compromised if this privilege is given to other entities.'
  resolution: 'To establish the recommended configuration via configuration profiles, set the following Settings Catalog path. Policy\Config\UserRights\AccessCredentialManagerAsTrustedCaller'