apiVersion: v1
kind: policy
spec:
  platform: windows
  name: 'STIG - Ensure ''Manage Auditing And Security Log'' is set to ''Enabled'''
  query: SELECT 1 FROM mdm_bridge WHERE mdm_command_input = '<SyncBody><Get><CmdID>1</CmdID><Item><Target><LocURI>./Device/Vendor/MSFT/Policy/Result/UserRights/ManageAuditingAndSecurityLog</LocURI></Target></Item></Get></SyncBody>' AND mdm_command_output = '1';
  purpose: Informational
  tags: framework:DISA-STIG, benchmark:DISA-STIG, platform:windows, control:win10-stig-v3r4:userrights-manageauditingandsecuritylog
  description: 'This user right determines which users can specify object access auditing options for individual resources, such as files, Active Directory objects, and registry keys. This security setting does not allow a user to enable file and object access auditing in general. You can view audited events in the security log of the Event Viewer. A user with this privilege can also view and clear the security log.'
  resolution: 'To establish the recommended configuration via configuration profiles, set the following Settings Catalog path. Policy\Config\UserRights\ManageAuditingAndSecurityLog'