apiVersion: v1
kind: policy
spec:
  platform: windows
  name: 'STIG - Ensure ''Allow Auto Connect To Wi Fi Sense Hotspots'' is set to ''Disabled'''
  query: SELECT 1 FROM mdm_bridge WHERE mdm_command_input = '<SyncBody><Get><CmdID>1</CmdID><Item><Target><LocURI>./Device/Vendor/MSFT/Policy/Result/Wifi/AllowAutoConnectToWiFiSenseHotspots</LocURI></Target></Item></Get></SyncBody>' AND mdm_command_output = '0';
  purpose: Informational
  tags: framework:DISA-STIG, benchmark:DISA-STIG, platform:windows, control:win10-stig-v3r4:wifi-allowautoconnecttowifisensehotspots
  description: 'Allow or disallow the device to automatically connect to Wi-Fi hotspots. Most restricted value is 0.'
  resolution: 'To establish the recommended configuration via configuration profiles, set the following Settings Catalog path. Policy\Config\Wifi\AllowAutoConnectToWiFiSenseHotspots'